apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: boqtzp7ml-python 
  janus-idp.io/tekton: boqtzp7ml-python
  backstage.io/kubernetes-id: boqtzp7ml-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: boqtzp7ml-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml