apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: boqtzp7ml-python
  janus-idp.io/tekton: boqtzp7ml-python
  backstage.io/kubernetes-id: boqtzp7ml-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: boqtzp7ml-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
